### ISSUE TITLE
Debian install tutorial

### ISSUE THREAD

**Issue by moimael** [feedbin/feedbin#29]
Hi,

I just started to write a tutorial on how to install feedbin on debian 7.

I made some progress but I'm stuck at creating the database.

Here are the step I took :

Install dependencies:

```
apt-get install libxslt-dev libxml2-dev redis-server postgresql postgresql-server-dev-all git libcurl4-openssl-dev
```

Create a feedbin user :

```
useradd -m -s /bin/bash -p $PASSWORD feedbin
```

Login as feedbin user :

```
su -l feedbin
cd
```

Clone feedbin git repo :

```
git clone https://github.com/feedbin/feedbin.git
```

Install RVM

```
curl -L get.rvm.io | bash -s stable
```

Install Ruby 2.0 :

```
rvm install 2.0
```

Make it default :

```
rvm use 2.0 --default
```

Create Gemset :

```
rvm gemset create feedbin
```

Use previously created Gemset as default :

```
rvm 2.0@feedbin --default
```

I created a feedbin database and a feedbin user in PostgreSQL with a password.

Here i'm not sure :

I edited the config/database.yml file

I added this, since I don't want the dev or test database :

```
production:
  adapter: postgresql
  encoding: unicode
  database: feedbin
  pool: 19
  username: feedbin
  password: my_password
  host: localhost
```

```
cd feedbin
bundle
```

then :

```
rake db:setup
```

And whatever I try, this command don't stop giving me errors. Ex: complaining about password not set for dev and test database (and also other errors), how can I disbale them ?

Thanks !
