### ISSUE TITLE
Should tweet previews include retweets/quotes?

### ISSUE THREAD

**Issue by endquote** [feedbin/feedbin#505]
I don't think they used to. This makes them very tall in the article list. [Example tweet](https://twitter.com/RebeccaFiebrink/status/1288019315820814336).

![Screen Shot 2020-07-28 at 6 43 09 AM](https://user-images.githubusercontent.com/330010/88673632-b3034400-d09d-11ea-8179-98193aca4dec.png)

**Comment by benubois** [comment]
Hi Josh,

I don't believe anything has changed here.

Thanks,

Ben

**Comment by endquote** [comment]
I ended up hiding them with a user style:

```css
.entries-column .quoted-summary {
    display: none !important;
}
```
