### ISSUE TITLE
Badly-behaved "..." tips

### ISSUE THREAD

**Issue by endquote** [feedbin/feedbin#637]
Two issues have come up recently with the "..." tips that appear over links.

They don't show up in the right place. I do have a custom stylesheet applied, and they are placed correctly if I remove it.

If a tip is showing when the selected article changes, the tip doesn't go away. This seems unrelated to the custom stylesheet.

This is in Safari 14.0.3.

https://user-images.githubusercontent.com/330010/113483024-39a2c900-9456-11eb-94eb-d7c0f299fb18.mov

```css
/* feedbin */

.feeds-column {
  zoom: 0.9 !important;
}

.entries-column {
  zoom: 0.9 !important;
}

h2.title {
  font-weight: normal !important;
}

.entry-header,
.tweet-header {
  zoom: 0.8 !important;
}

.entry-header h1 {
  font-weight: normal !important;
}

.entry-content {
  zoom: 1.2 !important;
}

/* entries have a lot of padding at the top */
.entry-inner {
  padding: 20px !important;
}

/* hide tweet quotes */
.entries-column .quoted-summary {
  display: none !important;
}

/* titles in post list don't need to be bold */
.entry-summary-link .title-wrap .title {
  font-weight: normal !important;
}
```
