### ISSUE TITLE
Subscribe Now Button Overflow

### ISSUE THREAD

**Issue by Polytonic** [feedbin/feedbin#95]
The `n Days Left -- Subscribe Now` button overflows on narrow layouts. 

![subscribe](https://cloud.githubusercontent.com/assets/5358453/2763898/f28dddba-ca0a-11e3-9dbd-8a2ffbcdce3e.PNG)
I see this under Chrome `v34.0.1847.116`, under both Windows 7 and OSX (10.9.2).

---

One option might be to truncate the button to just the number of days left, then expand to the full text on hover.  Perhaps something along the lines of the following?

``` css
.subscribe-promo {
    white-space: nowrap;
    overflow: hidden;
    width: __daysRemainingWidth__;
}

.subscribe-promo:hover {
    width: __TotalButtonWidth__;
}
```
